baseURL = "https://hoang-ho.github.io/"
languageCode = "en-us"
title = "Hoang Ho"
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 3


[params]
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "I'm an incoming Software Engineer at Apple. I was SDE intern at Amazon.com and Research intern at IBM Research, Yorktown Heights"
  MainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  # dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/hoang-ho"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/hoangnkho/"
  [[params.social]]
    name = "email"
    link = "hnho@umass.edu"  # no need for "mailto:" in the head